### ISSUE TITLE
The bank logo is missing

### ISSUE THREAD

**Issue by ggeorg0p** [Enartia/woo-payment-gateway-for-piraeus-bank#1]
Version 2.0.7 screenshot

![image](https://github.com/user-attachments/assets/ddec4939-ef65-4f6b-a4cf-f27acda0fe6b)

Version 3 screenshot

![image](https://github.com/user-attachments/assets/efff2d34-13e9-448e-bfe9-6d597d6ba06d)

**Comment by uprise10** [comment]
Fixed by #5
