### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by ggeorg0p** [Enartia/woo-payment-gateway-for-piraeus-bank#2]
Version 2.0.7 screenshot

![image](https://github.com/user-attachments/assets/36f5de66-148d-4e4e-ab9d-8e8decf85b6f)

Version 3 screenshot
![image](https://github.com/user-attachments/assets/8273b4ff-566e-4c56-bdf2-85d1025d1908)

As you may notice, the text in red, in version 3 is different than the one in version 2.0.7

**Comment by RaymondBakker** [comment]
If this is regarding the mandatory field, I think this issue may be fixed by https://github.com/Enartia/woo-payment-gateway-for-piraeus-bank/pull/4.

**Comment by uprise10** [comment]
@ggeorg0p Since this field is not mandatory anymore (fixed by the issue that @RaymondBakker mentioned), there is no need to display this text string anymore. So it's not available anymore in the PO-file, and I think therefor this ticket can be closed.
If you feel otherwise, feel free to re-open :)
